### ISSUE TITLE
Question about local wikipedia with ZIM and Kiwix-server

### ISSUE THREAD

**Issue by hakim-im** [el-tocino/localcroft#7]
Hi El Tocino

Thank you very much for you guide on all things local mycroft.
:)

Re. Wikipedia, I followed the easy method with Invader ZIM.
All went well and I can access my local wikipedia via web browser.

I am having issues getting mycroft to access this wiki though.
I edited the file wikipedia.py and changed the API_URL with the local IP (http://192.168.1.43:7998/) of the kiwix-serve: 
When querying mycroft  wikipedia skill, I get the error  WikipediaSkill | Error: Expecting value: line 1 column 1 (char 0)

Would you mind please sharing your config of the API_URL in wikipedia.py?

Many thanks.

**Comment by el-tocino** [comment]
Ahh--I haven't added anything for that yet.  Sorry!  I'll try and update later this week.

**Comment by hakim-im** [comment]
Thank you. Much appreciated! :)

**Comment by el-tocino** [comment]
It turns out kiwix doesn't implement an API function yet.  

Checking other methods to see if this is usable a different way, but I'm going to close this as it's a not likely to work with the wikipedia module ever.
